version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quickmarkdb
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quickmarkdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      # EF Core expects this format for UseNpgsql:
      DATABASE_URL: "Host=db;Port=5432;Database=quickmarkdb;Username=postgres;Password=root"

      # Optional but recommended JWT settings
      JWT__Secret: "K3yThat!sThirtyTwoCharactersLong"
      JWT__ValidIssuer: "quickmark-api"
      JWT__ValidAudience: "quickmark-client"

    ports:
      - "7045:80"  # Exposes your ASP.NET app on localhost:7045
