version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres #FIXME
      POSTGRES_PASSWORD: root #FIXME
      POSTGRES_DB: quickmarkdb
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quickmarkdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:root@db:5432/quickmarkdb" #FIXME