# python-processor/Dockerfile

FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    # Esetleg más szükséges rendszerfüggőségek, ha vannak
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir -r venv.txt \
    && pip install torch torchvision torchaudio
	
EXPOSE 8000

CMD ["python", "FlaskBackEndServer.py"]